aio_pika/message.py
tests/test_amqp.py

Make `message.Message` class to accept `None` values for `delivery_mode` keyword argument.
Relates to: #3

Make Message accept delivery_mode=None

---

aio_pika/channel.py
aio_pika/exchange.py
tests/test_amqp.py

Recently had a requirement for this in one of my projects, so I figured I'd submit the change. Clearly just a copy-paste job on the ``Queue.bind``/``Queue.unbind`` methods. I can add some tests for the changes if you'd like - just wasn't sure whether you preferred it get its own separate test case.

Exchange 'internal' option & exchange-to-exchange bindings

---

aio_pika/adapter.py

There is not implemented "update_handler" method which is critical for publishing messages with body size greater than 1 chunk.
For instance:
```python
import asyncio
from aio_pika import connect, Message
loop = asyncio.get_event_loop()
async def main():
connection = await connect("amqp://guest:guest@rabbit/", loop=loop)
channel = await connection.channel()
body = b'test' * 99999
message = Message(body)
await channel.default_exchange.publish(message, routing_key='')
await connection.close()
loop.run_until_complete(main())
```
```
$ python rabbitmq.py 
Failed to send data to client. Conection unexpected closed.
Traceback (most recent call last):
File "/tmp/venv/lib/python3.6/site-packages/aio_pika/channel.py", line 162, in _publish
self.__channel.basic_publish(queue_name, routing_key, …
```

Fix IOLoopAdapter

---

aio_pika/connection.py
aio_pika/robust_channel.py
aio_pika/robust_connection.py

It's useful to have some functional to run something that should be started after the connection established and all objects (channels, queues, exchanges, etc.) were declared in case it was after reconnect.
For instance, when I've had connected, opened channel and declared some queue, I must be sure that my queue is ready and I can use it. So after reconnect this initialization should be run too.
And, of course, reconnection interval as a handy parameter was added :)

Reconnection callback and interval

---

aio_pika/channel.py
aio_pika/robust_connection.py
tests/test_amqp.py

I guess callbacks should remain within connection, especially for connection lost and reconnects.

Fix callbacks calls

---

aio_pika/robust_connection.py

This seems to fix `AttributeError("'NoneType' object has no attribute 'channel'",)` mentioned in #75.
Would like to add a test to `test_amqp_robust.py` but given that the tests run against a real RabbitMQ server I'm not sure how to synchronise a server restart or similar in the context of a test.

Do not attempt to reconnect channels if there is no connection

---

aio_pika/exchange.py

RabbitMQ's consistent hash plugin is officially supported and included in the standard distribution. https://github.com/rabbitmq/rabbitmq-consistent-hash-exchange
However, because it's currently missing from the ExchangeType enum, it's awkward to declare such an exchange with with aio-pika. The fix is straightforward.

add the x-consistent-hash exchange type

---

aio_pika/channel.py
aio_pika/exchange.py
aio_pika/queue.py
aio_pika/robust_channel.py
aio_pika/robust_queue.py

Within the implementation of my worker class I use robust connection and declare exclusive queue. The queue must be really exclusive within all the worker instances and I correctly handle resource locks for this queue when connecting to the server. But I can't do that when reconnecting because of preliminary repeated declaration of this queue by the `RobustChannel.on_reconnect` implementation. So I suggest to add `robust` parameter for `RobustChannel.declare_exchange` and `RobustChannel.declare_queue` methods to allow disabling robustness of exchange or queue. With this parameters user can customize repeated declaration of any exchange or queue by specific algorithm using reconnect callbacks.

Allow to disable robustness of exchange or queue

---

aio_pika/adapter.py

There is an issue with current implementation: when Pika's ```Channel.basic_get``` method is called, (https://github.com/pika/pika/blob/master/pika/channel.py#L370) checks that the ```_on_getok_callback``` is not set (raising ```DuplicateGetOkCallback``` if it is not None), and then sets the callback.  This callback is cleared in Pika's ```Channel._on_getempty``` and ```Channel._on_getok```. 
**Aio-Pika**'s ```Channel``` implementation overrides ```_on_getempty``` but does not call it's super implementation, leaving the ```_on_getok_callback``` set, so, if the queue is empty, next time we try to use ```Channel.basic_get``` , the ```DuplicateGetOkCallback``` exception is raised.

Bugfix: _on_getempty should delete _on_getok_callback

---

aio_pika/adapter.py
aio_pika/connection.py
setup.py
tests/test_amqp.py

I don't know why, but pika >= 0.11.0 breaks robust connection (and maybe something else): #112.
**How to reproduce**
Checkout this branch, start simple consumer from [example](https://aio-pika.readthedocs.io/en/latest/quick-start.html#simple-consumer) and restart RabbitMQ. Everything should be OK. Then change pika's version from 0.10.0 to 0.11.0 and repeat: there will be a lot of errors.
So I suggest to downgrade pika's version to 0.10.0 now. Here I also removed usage of pika's asyncio adapter as pika==0.10.0 doesn't have it.
But maybe (I hope that) @mosquito or @lukebakken can resolve the issue and we wouldn't have to downgrade pika.

Downgrade pika to 0.10.0

---

aio_pika/channel.py

The timeout value for channel.declare_exchange(timeout) wasn't passed along to `yield from exchange.declare()`

declare_exchange in channel now timeout parameter to exchange.declare

---

docs/source/rabbitmq-tutorial/3-publish-subscribe.rst

Hello!
There is a small typo in tutorial docs (publish-subscribe part):
```The code for :download:`emit_log.py <examples/3-publish-subscribe/receive_logs.py>` script```
should be
```The code for :download:`receive_logs.py <examples/3-publish-subscribe/receive_logs.py>` script```
Thank you :)

fix rabbitmq-tutorial docs typo

---

aio_pika/patterns/master.py
tests/test_master.py

Without this fix, you probably get the following error in Python 3.4:
```AttributeError: 'method' object has no attribute '_is_coroutine'```

Handle coroutine wrapping for Python 3.4

---

aio_pika/channel.py

Related to [this issue][https://github.com/mosquito/aio-pika/issues/121].

Fixed ChannelClosed exception was never retrieved

---

aio_pika/queue.py

Sometimes when I close connection I get this error logs:
```
2018-06-13 01:07:23 ERROR Calling <bound method Channel._on_getempty of <aio_pika.adapter.Channel object at 0x10f6e3cc0>> for "1:Basic.GetEmpty" failed
Traceback (most recent call last):
File "/Users/roman/virtualenvs/messaging2/lib/python3.6/site-packages/pika/callback.py", line 236, in process
callback(*args, **keywords)
File "/Users/roman/virtualenvs/messaging2/src/aio-pika/aio_pika/adapter.py", line 235, in _on_getempty
self._on_getempty_callback(method_frame)
File "/Users/roman/virtualenvs/messaging2/src/aio-pika/aio_pika/queue.py", line 252, in _on_getempty
f.set_result(None)
asyncio.base_futures.InvalidStateError: invalid state
2018-06-13 01:07:23 ERROR Exception in callback BaseConnection._handle_events(fd=16, …
```

prevent set_results on cancelled future

---

aio_pika/channel.py
aio_pika/version.py

When we are trying to send message while connection is closed
we wait in loop until it is open again. However, because this
is in self._write_lock no other function can access this section
including creating new pika channel. Therefore new channel never
opens and then we get an exception that old channel has already
closed exception.
This should resolve my problem specified here https://github.com/mosquito/aio-pika/issues/112#issuecomment-432111405

Move waiting for connection outside of locked section

---

aio_pika/channel.py
aio_pika/connection.py
aio_pika/robust_connection.py
aio_pika/tools.py

Fixes robust reconnecting and the following errors during reconnecting:
1. Exception `RuntimeError("Can't initialize closed channel")`
2. Exception `InvalidStateError`:
```
ERROR:aio_pika.channel:Failed to send data to client (connection unexpectedly closed)
Traceback (most recent call last):
File "/home/decaz/workspace/aio-pika/aio_pika/channel.py", line 263, in _publish
self._channel.basic_publish(
AttributeError: 'NoneType' object has no attribute 'basic_publish'
Traceback (most recent call last):
File "/home/decaz/workspace/aio-pika/aio_pika/channel.py", line 263, in _publish
self._channel.basic_publish(
AttributeError: 'NoneType' object has no attribute 'basic_publish'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File …
```

RobustConnection fixes

---

aio_pika/pika/adapters/base_connection.py

Fix of the following exception:
```UnboundLocalError: local variable 'bw' referenced before assignment```
Refs #112

Fix UnboundLocalError exception

---

aio_pika/channel.py
aio_pika/queue.py
aio_pika/robust_queue.py
aio_pika/version.py
docs/source/index.rst
tests/test_amqp.py
tests/test_amqp_robust.py

On reconnect passive queues tries redeclared in creation mode and fails over and over again.

Queue redeclare fails on reconnect if queue is passive

---

aio_pika/pika/utils.py

When using or importing abstract base classes from Python's `collections` module, these must be explicitely used from `collections.abc` instead of from `collections` directly. This commit solves the resulting DeprecationWarning.

Fixed Deprecation Warnings in Python 3.7

---

docs/source/rabbitmq-tutorial/examples/4-routing/receive_logs_direct.py

Declaring a random queue, each consumer binds its **unique** queue with desired routing_key to the direct exchange
Before, the consumer declared the queue named 'task_queue'. That made each consumer to listener to the **same** queue. Even if bound to the direct exchange with different routing_key, the consumer was receiving all the message in round robin way.

Fix changing from named queue to random queue

---

aio_pika/__init__.py
aio_pika/version.py

Referencing `pool` from `aio_pika` currently fails with `AttributeError: module 'aio_pika' has no attribute 'pool'`. You can still import `pool` directly (e.g. `from aio_pika import pool`), but it would be nice to reference a bunch of things from a simple `import aio_pika`.
Exposing it in `aio_pika.__init__` does the trick.

Allow `pool` module to be referenced from `aio_pika`

---

aio_pika/adapter.py
aio_pika/connection.py
aio_pika/pika/adapters/base_connection.py
aio_pika/pika/connection.py

Laziest approach, this code could really leverage asyncio's high level connection stuff.
----
For #124 
This is mostly just a RFC, I don't expect this to get merged, but it works as expected and i'm fairly sure it's thread safe.
The most important change here, regardless of the approach taken, is to remove the connect() call from `pika.connection.Connection.__init__`, which can never be async, and to move it to an explicit call after creating the instance, so that it can be awaited.
I went for minimal but not quite API-clean changes - I don't know what API guarantees should be kept here, or what's the desired extent of changes to the vendored pika, if any.
At first I avoided changing the vendored pika but later I realized its BaseConnection is nothing like the upstream one, so I …

Make pika connections async, move _adapter_connect to a thread pool

---

aio_pika/message.py
tests/test_amqp.py

`HeaderProxy` has incorrect iterator behaviour, which breaks `Message.__copy__`.

Fix HeaderProxy bug

---

aio_pika/message.py
tests/test_amqp.py

`encode_timestamp` fails on `time.time_struct` value

Fix encode timestamp error on copy

---

aio_pika/pool.py

Usage of None is standard on Python for uninitialized objects, while Ellipsis is mostly used as a helper for slicing multidimensional lists/arrays.
Using None provides clarity and simplicity.
Signed-off-by: Antonio Gutierrez <chibby0ne@gmail.com>

Pool: use None instead of Elipsis for initial state

---

setup.py

To make the aio_pika package PEP-561 compatible, it needs to indicate
the presence of the marker file in the setup.py file. This ensures
installing the package as a typed package.
Currently if you run mypy on any package that uses aio_pika it errors out like:
```shell
error: Cannot find module named 'aio_pika'
```

Update setup.py to include py.typed marker file.

---

aio_pika/message.py

Unnecessary `None` assignments cause mypy to see these fields as `Optional` even though the have acutal value assigned in `__init__`

Removed None assignemnts to non-optional attributes.

---

aio_pika/queue.py

During debugging in stumbled on an odd return type of `Queue.bind` that seems to be a typo.
This appears to be inconsequential as the type is not checked by default.
Note that there is an actual runtime check in `Channel.rpc` for `valid_responses` and the return type is in fact `BindOk`.
I have not actually tested the patch as there isn't a test case where it fails.

fix return type of Queue.bind

---

aio_pika/channel.py
aio_pika/message.py
aio_pika/pool.py
aio_pika/robust_channel.py
setup.py

This change adds the `typing_extensions` module to allow support for Python 3.5 and 3.6 including PyPy.

Add typing_extensions for 3.5 and 3.6 support

---

aio_pika/message.py
tests/test_amqp.py

`HeadersProxy.__setitem__` has call to `format_headers` in order to format value, but `format_headers`, it seems, supposed to be called with entire headers mapping, not an individual value (and it will raise an AttributeError if called just with a string).
I've replaced the call of `format_headers(value)` in `HeadersProxy.__setitem__` code by `header_converter(value)` call to fix this bug.
Also, this PR features a test case for individual header set for the `Message` instance.

[Message] Fix: set header value on HeaderProxy

---

aio_pika/connection.py
aio_pika/exceptions.py
aio_pika/robust_connection.py

There is unexpected `return` statement within connection loop so `connect` method will return after the first iteration.

Fix robust connection

---

aio_pika/exchange.py

Hello, 
I think the type exchange restriction is strong. Sometimes you need exchange type which haven't been added yet. For example, has been created new plugin and __aio_pika__ has not been updated yet

Extended ExchangeType

---

README.rst
aio_pika/connection.py
aio_pika/exchange.py
aio_pika/message.py
aio_pika/queue.py
aio_pika/robust_connection.py
aio_pika/tools.py
docs/source/conf.py
docs/source/index.rst
docs/source/patterns.rst
docs/source/rabbitmq-tutorial/1-introduction.rst

* Mentions of `pika` are removed or changed to `aiormq`
* Renamed `aio_pika` -> `aio-pika`
* Some grammar corrections

Fix documentation

---

aio_pika/message.py

Fix misnamed variable & function.
My usage of the library looked fine, so was taking a look to verify that the variables were correctly converted for rabbitmq to process and noticed the MICROSECONDS variable and thought that was the problem, it wasn't but figured I'd fix this for you anyway.

A one thousandth of a second is a millisecond, not a microsecond

---

aio_pika/robust_connection.py

The following exception is observable: `AttributeError: 'NoneType' object has no attribute 'close'`.
@mosquito I think it's critical and should be released as soon as possible.

Fix robust connection cleanup

---

aio_pika/connection.py

I found a bug when getting heartbeat_last of a robust connection because of heartbeat_last is not a variable in rmq connection , actually rmq connection  use heartbeat_last_received instead. my env is :
```
(venv) root@ubuntu1804:~/workspace# pip list | grep pika
aio-pika                6.4.1     
(venv) root@ubuntu1804:~/workspace# 
(venv) root@ubuntu1804:~/workspace# pip list | grep rmq
aiormq                  3.2.0     
```
it can be tested by code below:
```
import asyncio
import aio_pika
import logging
logging.basicConfig(level=logging.DEBUG)
async def main(loop):
connection = await aio_pika.connect_robust("amqp://rabbitmq:123456@192.168.20.201:5672/", loop=loop)
print(connection.heartbeat_last)
if __name__ == "__main__":
loop = asyncio.get_event_loop() …
```

[fix] heartbeat_last

---

aio_pika/connection.py

Before the change loop that was passed to aiopika connection was not passed further to aiormq connection and it resulted in having two different loops:
After the change connection is properly passed as an argument further down and we have same instance everywhere:

Pass loop when connecting to aiormq

---

aio_pika/channel.py
aio_pika/robust_channel.py
aio_pika/robust_connection.py
aio_pika/robust_exchange.py
aio_pika/robust_queue.py
tests/test_amqp.py

It happens that the channel closes and you need to open it again. In case of robust connection currently this is possible using an inconvenient call:
```python
await channel.on_reconnect(
connection=channel._connection,
channel_number=channel._channel_number,
)
```
I suggest to make it as follows:
```python
await channel.reopen()
```
Thereby `on_reconnect` methods should be renamed to `restore` which mean more broad sense than just reconnection.

Add reopen method for channel

---

setup.py

There was no link from the PyPI page to this repository. This will make links appear on the left:

Add docs and github links to setup.py

---

aio_pika/robust_channel.py
tests/test_amqp_robust.py

Fixes #229 
I wasn't sure if to add tests as my approach is pretty simple...

Fix RobustChannel not reconnecting on duplicate named queue/exchanges

---

aio_pika/pool.py

This helps mypy determine the return type when using a pool like:
`async with self.connection_pool.acquire() as connection:`
or
`async with self.channel_pool.acquire() as channel:`
Without this, mypy was telling me to set type for the `connection` and `channel` variables.

Add generics to Pool and PoolItemContextManager

---

aio_pika/robust_connection.py

RobustConnection was reconnecting whenever the connection was lost,
even if the connection had been closed on pupose by invoking
`connection.close()`. The reconnect code now tests if a reconnect
attempt should be made at all by consulting `self._closed`.

Conditionally reconnect RobustConnection

---

.gitignore
aio_pika/channel.py
aio_pika/robust_channel.py
aio_pika/robust_exchange.py
docs/source/index.rst
tests/conftest.py
tests/test_amqp_robust_proxy.py

If connection is closed and Exchange instance from RobustChannel.default_exchange is assigned to some variable, then exchange is not restored.
```python
ch = await robust_conn.channel()
exchange = ch.default_exchange
await exchange.publish(b'message', 'some_queue')
```

Restore RobustChannel.default_exchange on reconnect

---

docs/source/rabbitmq-tutorial/1-introduction.rst
docs/source/rabbitmq-tutorial/2-work-queues.rst
docs/source/rabbitmq-tutorial/3-publish-subscribe.rst
docs/source/rabbitmq-tutorial/6-rpc.rst
docs/source/rabbitmq-tutorial/examples/1-introduction/receive.py
docs/source/rabbitmq-tutorial/examples/1-introduction/send.py
docs/source/rabbitmq-tutorial/examples/2-work-queues/new_task.py
docs/source/rabbitmq-tutorial/examples/2-work-queues/worker.py
docs/source/rabbitmq-tutorial/examples/3-publish-subscribe/emit_log.py
docs/source/rabbitmq-tutorial/examples/3-publish-subscribe/receive_logs.py
docs/source/rabbitmq-tutorial/examples/4-routing/emit_log_direct.py
docs/source/rabbitmq-tutorial/examples/4-routing/receive_logs_direct.py
docs/source/rabbitmq-tutorial/examples/5-topics/emit_log_topic.py
docs/source/rabbitmq-tutorial/examples/5-topics/receive_logs_topic.py
docs/source/rabbitmq-tutorial/examples/6-rpc/rpc_server.py

Fix rabbitmq tutorial documentation problems:
- There was a disparity between what the current tutorial was
explaining and what code snippet was showing
- Fixed formatting for current documentation tutorial snippets (in
rabbitmq tutorial)
- Fix disparity between line numbers in part 6 of tutorial and source
code
- Using `b' '.join(arg.encode() for arg in sys.argv[1:]` for getting user input in part 2 and 3 instead of `b' '.join(sys.argv[1:])` (later won't work in Python 3)

Improve documentation examples and snippets

---

aio_pika/channel.py
aio_pika/connection.py
aio_pika/robust_connection.py
tests/test_amqp.py
tests/test_amqp_robust.py

[This commit](https://github.com/mosquito/aio-pika/pull/316/commits/5d3d5451ef33d1e31828bb10cef45e037c44b6f8) introduced the possibility to only store weak references to callbacks in the `CallbackCollection` class. This commit subtly broke the interface by storing all callbacks only weak by default. This PR changes the default back to non-weak and exposes the `weak` parameter of the underlying methods.
Note: I wasn't able to run all tests, because `tests/test_amqp_robust_proxy.py::test_channel_fixture` hangs for me. 😕 
Fixes #331 and #332.

Fix breaking change in callback definition

---

aio_pika/connection.py

If write something like
```
rabbitmq_connection: aio_pika.Connection = await aio_pika.connect_robust(
f"amqp://{rabbitmq_option('username')}:{rabbitmq_option('password')}@{rabbitmq_option('host')}/"
)
async with rabbitmq_connection:
async with rabbitmq_connection.channel() as channel:
pass
```
You got warning `Channel already closed`
To solve this problem, I added a channel closedness check.

Fix call close on closed channels

---

aio_pika/channel.py

When True, this parameter doesn't change the methods behavior; when False, methods just return Exchange/Queue instance without declaring it, saving a round-trip.

Add `ensure` parameter to `get_exchange`/`get_queue`

---

setup.py

This just changes the `python_requires` in `setup.py` to use the version definition supported by PEP 345.
See [here](https://github.com/python-poetry/poetry/issues/4095#issuecomment-851065187) for how this has become an issue.

Make Python version compatible with PEP 345

---

aio_pika/robust_connection.py

Replace the full traceback with a simple inline string of the exception of the failed reconnect attempt.
The full traceback requires many lines and appear frequently in logs (default every 5 s) at high visibility (warning).
At the same time, the traceback offers very little useful extra information in addition to the exception string.

reduce verbosity of reconnect warnings

---

aio_pika/patterns/rpc.py
tests/test_amqp_robust_proxy.py

Brief description of the bug:
When we pause the channel from which we instantiate the RPC. A method with an incorrect signature is put into callbacks. Because of this, the following trace occurs:
```
Traceback (most recent call last):
File \"/usr/local/lib/python3.8/site-packages/aio_pika/tools.py\", line 166, in __call__
cb(self.__sender(), *args, **kwargs)
TypeError: on_close() takes from 1 to 2 positional arguments but 3 were given
```
Corrected of this issue https://github.com/mosquito/aio-pika/issues/361
Also added a reraise to tools, since the tests did not catch this bug

Fixed callback on_close for rpc #361

---

aio_pika/version.py
setup.py

`>3.6` --> `>=3.6`
Use post0 release, since there are no bug fixes or feature changes. Just
making the version requirements less strict. Not strictly SemVer, but
a variant used by PEP 440.

Issue 441 - Suport all versions of python3.6 for poetry

---

docs/source/rabbitmq-tutorial/2-work-queues.rst

It seems that the method name from `pika` was copied over, while in `aio-pika` it is renamed.

📝 Fix `basic_ack` -> `ack` in tutorial

---

docs/source/rabbitmq-tutorial/examples/3-publish-subscribe/receive_logs.py

In the third tutorial, the comment indicates the name of the declared queue as `"task_queue"`, but in fact the name of the queue is generated randomly.

📝 Fix logic typo in tutorial

---

aio_pika/connection.py

fix for issue #468 :
The problem seems to be the refactoring of the connect/connect_robust method. 
Now it passes the client_properties to make_url() which does not expect it, thus is becomes kwargs.
```
make_url(... **kwargs):
...
kw = kwargs # <- {'client_properties': {'connection_name': 'A writer connection'}}`
...
return URL.build(
....
query=kw)
```
yarl url.build should get  {'connection_name': 'A writer connection'}, not {'client_properties': {'connection_name': 'A writer connection'}}
The fix is, imho to add client_properties to the make_url arguments, and merge it with kw (similarly to the ssl_options).

cannot use client_properties issue #468

---

aio_pika/abc.py

Fixes #490 
`leaks_test.py`
```python
import asyncio
import logging
import aiomisc
from aiomisc.service.tracer import MemoryTracer
from aio_pika import connect_robust
async def main():
logging.basicConfig(level=logging.DEBUG)
counter = 0
while True:
connect = await connect_robust()
channel = await connect.channel()
await asyncio.sleep(0.001)
await channel.close()
await connect.close()
counter += 1
if not counter % 100:
logging.info("%d Connections done", counter)
aiomisc.run(main(), MemoryTracer(), log_format="rich")
```

Fix memory leaks on channel close

---

aio_pika/tools.py

Sometimes we have an issue with RabbitMQ in production, and we see a lot of these types of errors:
This appears to be caused by some task objects that are missing a done_callback. This in turn could cause exceptions to be swallowed, I **think**.
I wonder if something like this could fix it.

Prevent "Task exception was never retrieved" on timeout

---

aio_pika/channel.py
aio_pika/robust_channel.py
tests/test_memory_leak.py

I've found two places that keep references to the Channel object methods and that prevents `Garbage Collecter` from deleting the channel from the memory. As result, after restoring the connection the `RobustConnection` restores all already closed channels.
The issue reproduction steps:
1. Start locally RabbitMQ broker instance
2. Create RobustConnection to the broker and open some RobustChannel
3. Check in a panel (i.e. RabbitMQ management) that the channel is opened
4. Close the channel
5. Restart broker
6. Check that you already opened 2 channels

Fix memory leaks

---

aio_pika/queue.py

A wrong information (the default timeout) is being printed (instead of the supplied one in kwargs).

Fix timeout logging on QueueIterator

---

aio_pika/channel.py
aio_pika/connection.py
aio_pika/tools.py

Access to `asyncio.Future.exception()` should be protected from unexpected raise of `asyncio.CancelledError` exception.

Fix getting futures exceptions

---

aio_pika/queue.py

An exception is raised if `QueueIterator` is created with the consumer flag `no_ack`.
Added a check to ensure `nack` is not getting called when `QeueuIterator` is closed and `consumer` has `no_ack` option set to `True`.

Do not nack if consumer is no_ack in QueueIterator

---

.github/workflows/tests.yml
aio_pika/patterns/master.py

Fixed `queue_name` was set as `channel_name`

---

aio_pika/tools.py

If future.exception() is not called (even on cancelled futures), it seems Python will then log 'Task exception was never retrieved'. Rewriting this logic slightly should hopefully achieve the same functionality while preventing the Python errors.

Prevent 'Task exception was never retrieved'

---

aio_pika/__init__.py
pyproject.toml

Currently there's an implicit dependency on `pkg_resources` from `setuptools` to get the version of the package.  This makes the dependency explicit for Python 3.7 and avoids it entirely for 3.8+ which have `importlib.metadata` available.

Avoid implicitly depending on setuptools

---

aio_pika/exchange.py

Also switch to f-strings rather than %-formatting, modelled after
`Queue.__repr__`.

Amend Exchange.__repr__ to include class name

---

aio_pika/connection.py
aio_pika/robust_connection.py
tests/test_kwargs.py

I provide a fix, so that the kwargs are passed down through connection_class in aio_pika.connect_robust().
In current master branch specifying fail_fast has no effect and the default values are used.
Following code will fail on master branch:
```
import asyncio
import aio_pika
async def main():
con = await aio_pika.connect_robust(fail_fast="False")
async with con:
assert con.fail_fast == False
asyncio.run(main())
```
This PR fixes connect() and connect_robust() and extends and fixes the existing unit tests.

bugfix: kwargs not working in aio_pika connect_robust

---

docs/source/rabbitmq-tutorial/examples/6-rpc/rpc_client.py

Change to automatically handle acks of queues expecting rpc responses.
If the no_ack flag is False, the task resource is not removed from rabbitmq because the ack of the response message is not processed. The reason why explicit ack was not used is that there is no queue waiting for the ack of response.

Update example code of rpc tutorial

---

aio_pika/abc.py
aio_pika/queue.py

The master assumes that the message should be checked for not-none even if `fail=True` (default) and None is never returned.
```
msg = await queue.get()
assert msg is not None
```
The proposal avoids the need for such asserts by using `typing.Literal` and method overloads.

Improve type hints for queue.get()

---

README.rst
docs/source/index.rst

This is a raw exmaple of `See also` section what we talking about.
I had try to find some more examples and did it:
[Mela](https://github.com/uthunderbird/mela) - another one **aio-pika** wrapper, but maintainer looks like end of enthusiasm (so, I invite it to Propan collaborator and waiting for answer)
[aiormq](https://github.com/Polyconseil/aioamqp) - more **aiormq** alternative, whatever, it looks abandoned
[aiormq](https://github.com/mosquito/aiormq) - **aio-pika** core (you know), it can make sense to notice it here
[pika](https://pika.readthedocs.io/en/stable/modules/adapters/asyncio.html) - the official **RMQ** library, has an *asyncio* interface too. But it is implemented in some weird way, so I don't know what we should do with it.
Feel free to point me at any required changes.

Add `See also` section (#557)

---

docs/source/index.rst

My bad, I am not a .rst user, thus made a mistake
For some reason, github and sphinx are using the different .rst parsers (or differ from [this guide](https://thomas-cokelaer.info/tutorials/sphinx/rest_syntax.html#headings)) and the same README markup represents wrong in `aio-pika` sphinx doc: there no any `See also` sections subtitles.
So I fix It and now we have the following view:
Instead the current:

Fix `See also` Sphinx headers

---

aio_pika/robust_channel.py
tests/test_amqp_robust.py

@mosquito Here's a test that repro the infinite loop hang and a fix.
The last `declare_queue` is where the hang happen.
(See #565 )

Fix race condition in RobustChannel in reopen/ready

---

aio_pika/patterns/rpc.py

When handing on_close, futures were not properly popped from the futures list, causing an asyncio.exceptions.InvalidStateError when the connection is re-established and the response received.

Fix bug with RPC when handling on_close with a RobustConnection

---

aio_pika/queue.py

In the `Queue` class the Function `declare` takes an argument called `passive` according to docstrings.
Currently it does not.
This PR adds it as an optional parameter.
if no argument is given it will default to `self.passive`

Queue.declare() passive parameter not recognized

---

aio_pika/abc.py
aio_pika/patterns/base.py
aio_pika/patterns/master.py
aio_pika/patterns/rpc.py
aio_pika/queue.py

I've noticed that `__slots__` are defined in `Message`-classes, but they were not working as expected.
> When inheriting from a class without __slots__, the __dict__ and __weakref__ attribute of the instances will always be accessible.
https://docs.python.org/3/reference/datamodel.html?#object.__slots__
So all parent classes must also have `__slots__` to disable `__dict__` creation. That's what I did in this PR

Define empty __slots__ in base classes

---

docs/source/rabbitmq-tutorial/1-introduction.rst

To sync aio-pika's tutorial example with official tutorial's example

Add channel definition code to example in rabbitmq-tutorial/1-introduction.rst

---

aio_pika/abc.py
aio_pika/message.py
tests/test_message.py

This change can be breaking because timestamp of incoming message will now have timezone info (UTC by default).
Fixes #609.

Do not use deprecated datetime.utcnow and datetime.utcfromtimestamp

---

docs/source/rabbitmq-tutorial/4-routing.rst

on the [page](https://aio-pika.readthedocs.io/en/latest/rabbitmq-tutorial/4-routing.html#) while i was reading the doc.
I found this typo  **Somple** which bothers me.

fix: typo from somple to simple

---

aio_pika/exchange.py
tests/test_amqp.py

Close #636, close #556, close https://github.com/airtai/faststream/issues/1579
Exception was copied from https://github.com/mosquito/aiormq/blob/master/aiormq/channel.py#L145

fix: raise ChannelInvalidStateError at exchange.publish with closed channel

---

aio_pika/robust_channel.py
tests/test_amqp_robust.py

It's not possible to close the RobustChannel right now, it always reopens.

fix: RobustChannel should not reopen after close() call

---

aio_pika/robust_channel.py

Currently, `RobustChannel` uses `WeakSet` to track exchanges and queues for reconnection. This causes issues when the connection is lost, as the references to queues and exchanges may be garbage collected if there are no other references to them in the user's code. When the connection is restored, these objects aren't automatically recreated.
This PR changes the collections from `WeakSet` to regular `set` to ensure that all exchanges and queues created with `robust=True` are properly restored after reconnection, regardless of whether there are other references to them.
1. Replace `defaultdict(WeakSet)` with `defaultdict(set)` for both exchanges and queues
2. Update docstrings to clarify the behavior of the `robust` parameter
- **Positive**: Exchanges and queues will be properly restored …

Replace WeakSet with set for robust channels tracking

---

aio_pika/robust_channel.py

global_ was sent in set_qos, and cached in self._global_qos, but was not sent in subsequent qos calls upon reconnect, leading to potentially different channel behavior after reconnect
Fixes #583

Add global_ param to basic_qos call in RobustChannel _on_open method

---

aio_pika/tools.py

Since `__task_inner()` is spawned as an `asyncio.Task` using the `channel.closing.add_done_callback()`, the only place where it can be awaited for potential exceptions is under `UnderlayChannel.close()`. This is done by calling the `OneShotCallback.wait()` method. However, when the connection to RabbitMQ is severed, the callback call inside the `OneShotCallback` task can raise an error when trying to reopen the connection, and when this happens, the channel instance is replaced with a new channel, which has a new instance of `OneShotCallback`.
Because of this, the original `OneShotCallback` task is never awaited in the `UnderlayChannel.close()`. So, to properly check for potential exceptions in the original task, we would need to await it somewhere or call the `self.__task.exception()` …

Catch and log potential exception during the OneShotCallback task execution
