aio_pika/common.py, aio_pika/exchange.py, aio_pika/queue.py, aio_pika/tools.py, setup.py, tests/test_amqp.py, tox.ini
Спасибо за прекрасную библиотеку!
Небольшой рефакторинг:
1. Python 3.3 поддержка невозможно из-за `yarl` - небольшие изменения в `setup.py`
2. Python 3.4.2- 3.5.2- поддержка из за отсутствующих `loop.create_task` и `loop.create_future`
3. Там была бага с дважды `asyncio.coroutine` в `Queue.consume`
4. Поддержка синхронных коллбеков в `Queue.consume`, например для простого перекладывания в `asyncio.Queue`
=> Refactoring

.gitignore, aio_pika/message.py, tests/test_amqp.py
And a little check in related test. Also corrected .gitignore to fully ingnore .idea folder
=> Fixed message process on re-rejection

aio_pika/message.py, docs/source/rabbitmq-tutorial/3-publish-subscribe.rst, docs/source/rabbitmq-tutorial/4-routing.rst, tests/test_amqp.py
Hi, I've fixed some typos in docs and add multiple ack
=> docs typo fixes and multiple ack

aio_pika/channel.py, aio_pika/queue.py, docs/source/index.rst
declare_queue with new bool argument `passive`
=> add argument to declare queue passively

aio_pika/channel.py
=> Prevent error log for normal channel close.

aio_pika/channel.py, aio_pika/message.py, aio_pika/robust_connection.py
=> Connection lost callback and fixes

aio_pika/channel.py, aio_pika/exchange.py, aio_pika/robust_channel.py, aio_pika/robust_exchange.py, aio_pika/version.py, tests/test_amqp.py
Expose `passive` flag in `aio_pika`.
=> Allow declaring exchanges with 'passive' flag

aio_pika/connection.py, aio_pika/robust_connection.py, docs/source/examples/external-credentials.py, docs/source/quick-start.rst
That change allow to use ExternalCredentials. Now there is no way to use them
=> Use ExternalCredentials when no login provided

aio_pika/channel.py, aio_pika/connection.py, tests/_async_await_cases.py, tests/test_amqp.py
=> Added asynchronous context manager support for channels

aio_pika/queue.py
Allow kwargs to be forwarded to call to consume() from call to queue.iterator()
=> Allow kwargs to be passed to queue.iterator

aio_pika/pool.py, tests/test_pool.py
Inspired by #173 from @krieghan.
=> [fix] add abstract pool

aio_pika/channel.py, aio_pika/exchange.py, aio_pika/queue.py, aio_pika/transaction.py
Also fixes duplicate exception on queue declaration error.
=> Fix race condition on callback timeout

README.rst
Signed-off-by: Antonio Gutierrez <chibby0ne@gmail.com>
=> README: provide development and testing steps

aio_pika/pool.py
Having arguments enables flexible and reusable pool creation functions.
Signed-off-by: Antonio Gutierrez <chibby0ne@gmail.com>
=> pool: enable arguments for pool constructor

aio_pika/connection.py, tests/test_amqp.py, tests/test_amqp_robust.py, tests/test_amqp_without_publisher_confirms.py, tests/test_amqp_without_publisher_confirms_robust.py, tests/test_master.py, tests/test_pool.py, tests/test_rpc.py
=> Fix URL building

aio_pika/queue.py, aio_pika/robust_queue.py
=> Fix routing key handling

aio_pika/message.py, tests/test_amqp.py
=> Handle int in headers

aio_pika/patterns/master.py
Otherwise, there is no way to specify `reject_on_redelivered=True` when using `Master` pattern.
=> Allow to specify `requeue=` and `reject_on_redelivered=` in Master pattern

aio_pika/connection.py
Not sure if it's the best fix, but works for my case.
=> Connection won't be closed in __del__ if it wasn't open. Fixes #219

aio_pika/exceptions.py, aio_pika/robust_connection.py
* Added `RuntimeError` to `CONNECTION_EXCEPTIONS`
* Handle `CONNECTION_EXCEPTIONS` at channel reconnect
=>  Make RobustConnection more robust

aio_pika/connection.py, aio_pika/robust_connection.py, tests/test_connect.py
Some type hints were also fixed.
=> Add missing connection timeout parameter

aio_pika/message.py
solves https://github.com/mosquito/aio-pika/issues/251
I'm no mypy pro, hoping it's right
=> Added typing on process method

docs/source/rabbitmq-tutorial/examples/6-rpc/rpc_client.py
just repeat loop name for global variable
=> [fix] rpc_client loop

aio_pika/exchange.py, tests/test_amqp.py
=> [fix] allow str as an exchange type

aio_pika/connection.py, aio_pika/robust_connection.py
=> [fix] pass connect kwargs

aio_pika/connection.py, aio_pika/patterns/master.py, aio_pika/patterns/rpc.py, aio_pika/pool.py, aio_pika/queue.py, aio_pika/robust_connection.py, aio_pika/tools.py, setup.py, tests/__init__.py, tests/test_amqp.py, tests/test_amqp_robust.py, tox.ini
Fixes stuck RobustConnectionwhen a queue has been declared with the exclusive flag.
=> Stucking RobustConnection

aio_pika/channel.py, aio_pika/robust_channel.py, tests/test_amqp.py
=> Add `global_` parameter to `Channel.set_qos` method

aio_pika/robust_exchange.py, aio_pika/robust_queue.py, tests/test_amqp_robust.py
As it is already done for `RobustChannel.declare_exchange` and `RobustChannel.declare_queue`.
=> Add robust parameters

aio_pika/robust_channel.py
I made declare_exchange in RobustChannel like Channel.
=> Fix type hint

aio_pika/robust_channel.py, aio_pika/robust_connection.py
https://github.com/mosquito/aio-pika/issues/284
=> Fix memory leak

aio_pika/connection.py, aio_pika/types.py
=> fix type annotation and documentation for Connection.add_close_callback

aio_pika/channel.py
https://github.com/mosquito/aio-pika/issues/281
=> Add get methods for exchange and queue

aio_pika/channel.py, aio_pika/message.py, aio_pika/queue.py, aio_pika/robust_channel.py, aio_pika/robust_connection.py, aio_pika/robust_exchange.py, aio_pika/robust_queue.py, tests/test_amqp.py
=> Reopen method

aio_pika/robust_connection.py
https://github.com/mosquito/aio-pika/issues/305#issuecomment-601619158
=> Fix reconnecting on a closed connection

aio_pika/queue.py
https://github.com/mosquito/aio-pika/issues/325
=> Fix timeout onto read messages

README.rst, docs/source/conf.py, noxfile.py, pylava.ini, setup.py
Some small improvements to the readability of the README.
I have started messing around with `aio-pika` and thought that  I would work on the documentation a bit as I go through it, so I set up for that leveraging [nox](https://nox.thea.codes/en/stable/).
HTH.
=> Improve the docs a bit

aio_pika/channel.py
Remove method doesn't accept `weak`.
=> Fix call remove_close_callback

aio_pika/exchange.py
=> fix: add missing type hint on exchange publish method

docs/source/rabbitmq-tutorial/examples/2-work-queues/worker.py
Without async function `on_message` will raise an error:
```
async with message.process():
^
SyntaxError: 'async with' outside async function
```
=> Added async before 'on_message' function

README.rst
When I am using this library, I cannot find the demonstration of how can I connect with hostname and password before I read the source code.
=> Add illustration of connect via hostname, password, etc.

aio_pika/robust_queue.py
=> Generated anonymous queue name may conflict (fix #485)

aio_pika/patterns/rpc.py
It's useful to be able to show exceptions on the host.
Related issue: https://github.com/mosquito/aio-pika/issues/502
=> RPCs: Show exceptions on Host (remote side)

docs/source/rabbitmq-tutorial/1-introduction.rst, docs/source/rabbitmq-tutorial/2-work-queues.rst, docs/source/rabbitmq-tutorial/examples/2-work-queues/new_task_initial.py, docs/source/rabbitmq-tutorial/examples/2-work-queues/tasks_worker.py
Fixes #548 
I tried fixing some minor issues and continuity errors in the documentation.
=> Documentation fixes

aio_pika/robust_channel.py, tests/test_amqp_robust.py
=> Fix reopen of robust channel after close

aio_pika/robust_channel.py
=> Fix restore bug of RobustChannel

aio_pika/queue.py
=> Revert "Queue.declare() passive parameter not recognized"

aio_pika/robust_connection.py
Fix for the crash reported in #589 unfortunately not tested to verify if the fix is complete.
=> Fix possible error iterating on connection channels during concurrent update

docs/source/index.rst
Fix for a small typo on the main page
=> Fix typo in index.rst
